### ISSUE TITLE
Unknown intel compiler version (error: _AX_COMPILER_VERSION_INTEL)

### ISSUE THREAD

**Issue by ben-ljmu** [SWIFTSIM/swiftsim#7] opened 2018-12-12 12:30 UTC
Hi, 

We're having difficulty compiling the code on Ubuntu 18.04.1 using ICC version 18.0.1.
After running **./autogen**, using **./configure CC=icc MPICC=mpicc** exits with the following error:

```
checking for C compiler version... configure: error: in `/path/to/files':
configure: error: _AX_COMPILER_VERSION_INTEL unknown intel compiler version
```

However, using the exact same compiler on Ubuntu 16.04.5 seems to work fine. 

Hardcoding the version number using `ax_cv_c_compiler_version="18.0.1"` lets the configure step complete successfully (although CFLAGS have to be set manually).

Thanks!

**Comment by pwdraper** [comment] 2018-12-12 17:10
We've not seen that one before. Odd that it changes between Ubuntus. Can you attach the files
`config.log` and `configure` from a failed attempt?

**Comment by ben-ljmu** [comment] 2018-12-13 15:33
It does seem strange. I've attached both files from a failed attempt below.
Thanks again! 

[config.log](https://github.com/SWIFTSIM/swiftsim/files/2676631/config.log)
[configure.txt](https://github.com/SWIFTSIM/swiftsim/files/2676633/configure.txt)

**Comment by pwdraper** [comment] 2018-12-13 16:02
Thanks, so the problem is new support for the types `_Float32 _Float64` and others see:

  https://software.intel.com/en-us/forums/intel-c-compiler/topic/777003

The fix looks scheduled for the 2019 releases, maybe. In the meanwhile the only
work around is to define these missing types to your  `CFLAGS`:
```
 ./configure CFLAGS="-D_Float32=float -D_Float32x=float -D_Float64='long double' -D_Float64x='long double'"
```
I'm guessing. You may need to work on the quotes.

**Comment by JBorrow** [comment] 2019-04-05 16:11
Is this problem fixed now?

**Comment by ben-ljmu** [comment] 2019-04-05 16:16
Yep, there's no error when using the 2019 Intel compiler. 
Thanks

**Closed** 2019-04-05 16:16 UTC
